# Expo React Native GitHub Pages Deployment
name: Build
on:
  push:
    branches: ['main']
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Install deployment tool
        run: npm i gh-pages
      - name: Build app
        run: npm run build
      - name: Deploy app
        run: npm run deploy
